#!/bin/bash

function gvm {
    bash -c '. ~/.gvm/bin/gvm-init.sh; gvm "$@"' gvm $@
}

function addAppsPath {
    for program in $gvmPrograms; do
        export PATH=$PATH:~/.gvm/$program/current/bin
    done
}

function execApp {
    addAppsPath
    command $@
}

function printUsage {
    echo """
Usage: gw <gvm command>
       gw <application>

   gvm commands:
      you can use a all gvm commands except 'use'. Instead, use 'default'

   applications:
      you can use any of the following:
      gaiden gradle grails griffon groovy groovyserv lazybones springboot vertx
"""
}

function filterUse {
    echo """\
WARNING: avoid the 'gvm use' command. Instead, use 'gvm default'"""
    printUsage
}

gvmPrograms='gaiden gradle grails griffon groovy groovyserv lazybones springboot vertx grape groovyc groovyConsole groovydoc groovysh java2groovy startGroovy'

if [ $# -eq 0 ]; then
    printUsage
elif [[ $1 == "use" ]]; then
    filterUse
elif [[ $1 == "help" || $1 == "-help" || $1 == "--help" ]]; then
    printUsage
elif [[ $gvmPrograms =~ (^| )$1($| ) ]]; then
    execApp $@
else
    gvm $@
fi
